version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: erp_db
    ports:
      - '5432:5432'
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
